import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';

import './globals.css';

const NAV_MENU = [
  {
    title: 'Documentation',
    href: '/docs',
  },
  {
    title: 'Github',
    href: '/github',
  },
];
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="max-w-[1740px] px-8 py-4 mx-auto">
          <div className="flex items-center justify-between">
            <a href="/">
              <div className="flex items-center cursor-pointer">
                <Image src="" alt="supalogo" width="64" height="66" />
                <span className="text-3xl font-bold ml-4">Blast Frontend</span>
              </div>
            </a>
            <nav className="flex items-center">
              <ul className="flex items-center">
                {NAV_MENU.map((menu) => (
                  <li key={menu.title} className="mr-8 hover:text-[#F85150]">
                    <Link href={menu.href}>{menu.title}</Link>
                  </li>
                ))}
              </ul>
              <button
                className={
                  'btn bg-[#F85150] px-4 py-2 rounded-lg text-white font-bold uppercase'
                }
              >
                {'Connect wallet'}
              </button>
            </nav>
          </div>
        </header>
        <main className="flex min-h-screen flex-col items-center justify-between px-24 py-12">
          {children}
        </main>
      </body>
    </html>
  );
}
